DATA CLEANING AND DATA PREPROCESSING
1. Data cleaning is the process of changing or eliminating garbage,incorrect,duplcate or incomplete values
2. Data Preprocessing - Identifying what and which type of values are lost and filling them 

DATA CLEANING CYCLE STAGES
1. Importing dataset
2. Merging dataset
3. Re-build missing data
4. Standardize the format 
5. Normalise
6. De-Duplicate
7. Verify and Enrich

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
print(df)


        one       two     three
a -1.510030 -0.259332 -0.731306
c -0.341762 -1.228631  0.589450
e  0.360549 -0.761814  1.456560
f -0.375046 -0.609064 -0.260023
h  1.141701  1.550250  2.353629


In [3]:
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print(df1)

        one       two     three
a -1.510030 -0.259332 -0.731306
b       NaN       NaN       NaN
c -0.341762 -1.228631  0.589450
d       NaN       NaN       NaN
e  0.360549 -0.761814  1.456560
f -0.375046 -0.609064 -0.260023
g       NaN       NaN       NaN
h  1.141701  1.550250  2.353629


2 .CHECKING THE MISSING VALUE USING

In [5]:
a = df1['one'].isnull()
b = df1['two'].isnull()
c = df1['three'].isnull()
print(a)
print(b)
print(c)

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool
a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: two, dtype: bool
a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: three, dtype: bool


REPLACING THE ISSING VALUE

In [ ]:
print(df1)
print("NaN replaced with '0':")
print(df1.fillna(0))

        one       two     three
a -1.286262 -0.895527 -1.136792
b       NaN       NaN       NaN
c -0.522502  0.385919  0.251853
d       NaN       NaN       NaN
e -0.348278  2.596694  0.756616
f -0.211520 -0.069118  1.508077
g       NaN       NaN       NaN
h  1.150185  0.681784  0.375253
NaN replaced with '0':
        one       two     three
a -1.286262 -0.895527 -1.136792
b  0.000000  0.000000  0.000000
c -0.522502  0.385919  0.251853
d  0.000000  0.000000  0.000000
e -0.348278  2.596694  0.756616
f -0.211520 -0.069118  1.508077
g  0.000000  0.000000  0.000000
h  1.150185  0.681784  0.375253


FILLING NA CAN BE DONE IN TWO WAYS
1. FORMARD - pad/fill
2. BACKWARD - dfill

In [ ]:
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print("Before Filling")
print(df1)
print("After Filling")
print(df1.fillna(method='pad'))

Before Filling
        one       two     three
a -1.286262 -0.895527 -1.136792
b       NaN       NaN       NaN
c -0.522502  0.385919  0.251853
d       NaN       NaN       NaN
e -0.348278  2.596694  0.756616
f -0.211520 -0.069118  1.508077
g       NaN       NaN       NaN
h  1.150185  0.681784  0.375253
After Filling
        one       two     three
a -1.286262 -0.895527 -1.136792
b -1.286262 -0.895527 -1.136792
c -0.522502  0.385919  0.251853
d -0.522502  0.385919  0.251853
e -0.348278  2.596694  0.756616
f -0.211520 -0.069118  1.508077
g -0.211520 -0.069118  1.508077
h  1.150185  0.681784  0.375253


In [ ]:
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print("Before Filling")
print(df1)
print("After Filling")
print(df1.fillna(method='bfill'))

Before Filling
        one       two     three
a -1.286262 -0.895527 -1.136792
b       NaN       NaN       NaN
c -0.522502  0.385919  0.251853
d       NaN       NaN       NaN
e -0.348278  2.596694  0.756616
f -0.211520 -0.069118  1.508077
g       NaN       NaN       NaN
h  1.150185  0.681784  0.375253
After Filling
        one       two     three
a -1.286262 -0.895527 -1.136792
b -0.522502  0.385919  0.251853
c -0.522502  0.385919  0.251853
d -0.348278  2.596694  0.756616
e -0.348278  2.596694  0.756616
f -0.211520 -0.069118  1.508077
g  1.150185  0.681784  0.375253
h  1.150185  0.681784  0.375253


DROP MISSING VALUES

In [ ]:
df = pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
print(df)
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print(df1)
print("Drop the Missing Values")
print(df1.dropna())

        one       two     three
a  1.521844 -0.710664 -1.533465
c  0.209762  0.072368  0.779785
e  0.670220 -0.338005 -0.378979
f  0.151283  1.747091  0.919902
h  0.882230 -1.690014  0.913879
        one       two     three
a  1.521844 -0.710664 -1.533465
b       NaN       NaN       NaN
c  0.209762  0.072368  0.779785
d       NaN       NaN       NaN
e  0.670220 -0.338005 -0.378979
f  0.151283  1.747091  0.919902
g       NaN       NaN       NaN
h  0.882230 -1.690014  0.913879
Drop the Missing Values
        one       two     three
a  1.521844 -0.710664 -1.533465
c  0.209762  0.072368  0.779785
e  0.670220 -0.338005 -0.378979
f  0.151283  1.747091  0.919902
h  0.882230 -1.690014  0.913879


REPLACE MISSING (OR) GENERIC VALUES

In [ ]:
df= pd.DataFrame({'one':[10,20,30,40,50,2000],'two':[1000,0,30,40,50,60]})
print("Before Replacement")
print(df)
print("After Replacement")
print(df.replace({1000:10,2000:60,0:20}))

Before Replacement
    one   two
0    10  1000
1    20     0
2    30    30
3    40    40
4    50    50
5  2000    60
After Replacement
   one  two
0   10   10
1   20   20
2   30   30
3   40   40
4   50   50
5   60   60


In [ ]:
df = pd.read_csv('/workspaces/DAV/tested.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


DROPING THE COLUMNS THAT ARE NOT REQUIRED

In [ ]:
cols=['Name','Ticket','Cabin']
df=df.drop(cols,axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         417 non-null    float64
 8   Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 29.5+ KB


DROP THE ROWS HAVING NO VALUES

In [ ]:
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 331 entries, 0 to 415
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  331 non-null    int64  
 1   Survived     331 non-null    int64  
 2   Pclass       331 non-null    int64  
 3   Sex          331 non-null    object 
 4   Age          331 non-null    float64
 5   SibSp        331 non-null    int64  
 6   Parch        331 non-null    int64  
 7   Fare         331 non-null    float64
 8   Embarked     331 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 25.9+ KB


CREATING DUMMY VARIABLES

In [ ]:
dummies = []
cols = ['Pclass','Sex','Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))
    

CONCATENATE THE VALUES WITH DATA FRAME

titanic_dummies = pd.concat(dummies,axis=1)
df = pd.concat((df,titanic_dummies),axis=1)
df

REMOVE THE UNWANTED COLUMNS

In [ ]:
df = df.drop(['Pclass','Sex','Embarked'],axis=1)

TAKE CARE OF MISSING DATA

In [ ]:
print(df['Age'].isnull())
df['Age'] = df['Age'].interpolate()
print(df)

0      False
1      False
2      False
3      False
4      False
       ...  
409    False
411    False
412    False
414    False
415    False
Name: Age, Length: 331, dtype: bool
     PassengerId  Survived   Age  SibSp  Parch      Fare      1      2      3  \
0            892         0  34.5      0      0    7.8292  False  False   True   
1            893         1  47.0      1      0    7.0000  False  False   True   
2            894         0  62.0      0      0    9.6875  False   True  False   
3            895         0  27.0      0      0    8.6625  False  False   True   
4            896         1  22.0      1      1   12.2875  False  False   True   
..           ...       ...   ...    ...    ...       ...    ...    ...    ...   
409         1301         1   3.0      1      1   13.7750  False  False   True   
411         1303         1  37.0      1      0   90.0000   True  False  False   
412         1304         1  28.0      0      0    7.7750  False  False   True   
414        

NORMALISATION OR MIN MAX SCALER AND STANDARDIZATION

NORMALISATION : Rescalling data from original range so that all values are within the new range of 0 and 1
y = (X - )

In [ ]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5,0],[0,10],[1,18]]
scaler = MinMaxScaler()
print(scaler.fit(data))
MinMaxScaler()
print(scaler.data_max_)
print(scaler.transform(data))

MinMaxScaler()
[ 1. 18.]
[[0.         0.11111111]
 [0.25       0.        ]
 [0.5        0.55555556]
 [1.         1.        ]]


STANDARDIZING a dataset involves  re-scalling
sd = sqrt(sum((x-mean)^2)) / count(x))

In [ ]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler
data = asarray([[100,0.001],[8,0.05],[50,0.005],[88,0.07],[4,0.1]])
print(data)
scaler = StandardScaler()
scaled = scaler.fit_transform(data)
print(scaled)

[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]
