DATA CLEANING AND DATA PREPROCESSING
1. Data cleaning is the process of changing or eliminating garbage,incorrect,duplcate or incomplete values
2. Data Preprocessing - Identifying what and which type of values are lost and filling them 

DATA CLEANING CYCLE STAGES
1. Importing dataset
2. Merging dataset
3. Re-build missing data
4. Standardize the format 
5. Normalise
6. De-Duplicate
7. Verify and Enrich

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
print(df)


        one       two     three
a  0.626886 -0.139013 -1.310006
c -1.248152 -1.894186 -0.395506
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
h  0.283646  0.202188 -1.407271


In [3]:
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print(df1)

        one       two     three
a  0.626886 -0.139013 -1.310006
b       NaN       NaN       NaN
c -1.248152 -1.894186 -0.395506
d       NaN       NaN       NaN
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
g       NaN       NaN       NaN
h  0.283646  0.202188 -1.407271


2 .CHECKING THE MISSING VALUE USING isnull()

In [19]:
print(df1['one'].isnull())
print(df1['two'].isnull())
print(df1['three'].isnull())

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool
a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: two, dtype: bool
a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: three, dtype: bool


REPLACING THE ISSING VALUE

In [5]:
print(df1)
print("NaN replaced with '0':")
print(df1.fillna(0))

        one       two     three
a  0.626886 -0.139013 -1.310006
b       NaN       NaN       NaN
c -1.248152 -1.894186 -0.395506
d       NaN       NaN       NaN
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
g       NaN       NaN       NaN
h  0.283646  0.202188 -1.407271
NaN replaced with '0':
        one       two     three
a  0.626886 -0.139013 -1.310006
b  0.000000  0.000000  0.000000
c -1.248152 -1.894186 -0.395506
d  0.000000  0.000000  0.000000
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
g  0.000000  0.000000  0.000000
h  0.283646  0.202188 -1.407271


FILLING NA CAN BE DONE IN TWO WAYS
1. FORMARD - pad/fill
2. BACKWARD - bfill

In [6]:
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print("Before Filling")
print(df1)
print("After Filling")
print(df1.fillna(method='pad'))

Before Filling
        one       two     three
a  0.626886 -0.139013 -1.310006
b       NaN       NaN       NaN
c -1.248152 -1.894186 -0.395506
d       NaN       NaN       NaN
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
g       NaN       NaN       NaN
h  0.283646  0.202188 -1.407271
After Filling
        one       two     three
a  0.626886 -0.139013 -1.310006
b  0.626886 -0.139013 -1.310006
c -1.248152 -1.894186 -0.395506
d -1.248152 -1.894186 -0.395506
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
g  0.124238 -0.163449  0.185413
h  0.283646  0.202188 -1.407271


In [7]:
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print("Before Filling")
print(df1)
print("After Filling")
print(df1.fillna(method='bfill'))

Before Filling
        one       two     three
a  0.626886 -0.139013 -1.310006
b       NaN       NaN       NaN
c -1.248152 -1.894186 -0.395506
d       NaN       NaN       NaN
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
g       NaN       NaN       NaN
h  0.283646  0.202188 -1.407271
After Filling
        one       two     three
a  0.626886 -0.139013 -1.310006
b -1.248152 -1.894186 -0.395506
c -1.248152 -1.894186 -0.395506
d -0.943090 -0.799495 -0.052024
e -0.943090 -0.799495 -0.052024
f  0.124238 -0.163449  0.185413
g  0.283646  0.202188 -1.407271
h  0.283646  0.202188 -1.407271


DROP MISSING VALUES

In [8]:
df = pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
print(df)
df1 = df.reindex(['a','b','c','d','e','f','g','h'])
print(df1)
print("Drop the Missing Values")
print(df1.dropna())

        one       two     three
a -0.241820  0.244354  1.088755
c  1.513813  0.672475 -0.332177
e -2.009243  0.680439  2.372903
f -0.613402 -0.093560  0.513483
h -1.243461  0.423936 -0.034419
        one       two     three
a -0.241820  0.244354  1.088755
b       NaN       NaN       NaN
c  1.513813  0.672475 -0.332177
d       NaN       NaN       NaN
e -2.009243  0.680439  2.372903
f -0.613402 -0.093560  0.513483
g       NaN       NaN       NaN
h -1.243461  0.423936 -0.034419
Drop the Missing Values
        one       two     three
a -0.241820  0.244354  1.088755
c  1.513813  0.672475 -0.332177
e -2.009243  0.680439  2.372903
f -0.613402 -0.093560  0.513483
h -1.243461  0.423936 -0.034419


REPLACE MISSING (OR) GENERIC VALUES

In [9]:
df= pd.DataFrame({'one':[10,20,30,40,50,2000],'two':[1000,0,30,40,50,60]})
print("Before Replacement")
print(df)
print("After Replacement")
print(df.replace({1000:10,2000:60,0:20}))

Before Replacement
    one   two
0    10  1000
1    20     0
2    30    30
3    40    40
4    50    50
5  2000    60
After Replacement
   one  two
0   10   10
1   20   20
2   30   30
3   40   40
4   50   50
5   60   60


In [10]:
df = pd.read_csv('/workspaces/DAV/tested.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


DROPING THE COLUMNS THAT ARE NOT REQUIRED

In [11]:
cols=['Name','Ticket','Cabin']
df=df.drop(cols,axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         417 non-null    float64
 8   Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 29.5+ KB


DROP THE ROWS HAVING NO VALUES

In [12]:
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 331 entries, 0 to 415
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  331 non-null    int64  
 1   Survived     331 non-null    int64  
 2   Pclass       331 non-null    int64  
 3   Sex          331 non-null    object 
 4   Age          331 non-null    float64
 5   SibSp        331 non-null    int64  
 6   Parch        331 non-null    int64  
 7   Fare         331 non-null    float64
 8   Embarked     331 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 25.9+ KB


CREATING DUMMY VARIABLES

In [13]:
dummies = []
cols = ['Pclass','Sex','Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))
    

CONCATENATE THE VALUES WITH DATA FRAME

In [14]:
titanic_dummies = pd.concat(dummies,axis=1)
df = pd.concat((df,titanic_dummies),axis=1)
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch      Fare  \
0            892         0       3    male  34.5      0      0    7.8292   
1            893         1       3  female  47.0      1      0    7.0000   
2            894         0       2    male  62.0      0      0    9.6875   
3            895         0       3    male  27.0      0      0    8.6625   
4            896         1       3  female  22.0      1      1   12.2875   
..           ...       ...     ...     ...   ...    ...    ...       ...   
409         1301         1       3  female   3.0      1      1   13.7750   
411         1303         1       1  female  37.0      1      0   90.0000   
412         1304         1       3  female  28.0      0      0    7.7750   
414         1306         1       1  female  39.0      0      0  108.9000   
415         1307         0       3    male  38.5      0      0    7.2500   

    Embarked      1      2      3  female   male      C      Q      S  
0          Q  False  False   True   False   True  False   True  False  
1          S  False  False   True    True  False  False  False   True  
2          Q  False   True  False   False   True  False   True  False  
3          S  False  False   True   False   True  False  False   True  
4          S  False  False   True    True  False  False  False   True  
..       ...    ...    ...    ...     ...    ...    ...    ...    ...  
409        S  False  False   True    True  False  False  False   True  
411        Q   True  False  False    True  False  False   True  False  
412        S  False  False   True    True  False  False  False   True  
414        C   True  False  False    True  False   True  False  False  
415        S  False  False   True   False   True  False  False   True  

[331 rows x 17 columns]

REMOVE THE UNWANTED COLUMNS

In [15]:
df = df.drop(['Pclass','Sex','Embarked'],axis=1)

TAKE CARE OF MISSING DATA

In [16]:
print(df['Age'].isnull())
df['Age'] = df['Age'].interpolate()
print(df)

0      False
1      False
2      False
3      False
4      False
       ...  
409    False
411    False
412    False
414    False
415    False
Name: Age, Length: 331, dtype: bool
     PassengerId  Survived   Age  SibSp  Parch      Fare      1      2      3  \
0            892         0  34.5      0      0    7.8292  False  False   True   
1            893         1  47.0      1      0    7.0000  False  False   True   
2            894         0  62.0      0      0    9.6875  False   True  False   
3            895         0  27.0      0      0    8.6625  False  False   True   
4            896         1  22.0      1      1   12.2875  False  False   True   
..           ...       ...   ...    ...    ...       ...    ...    ...    ...   
409         1301         1   3.0      1      1   13.7750  False  False   True   
411         1303         1  37.0      1      0   90.0000   True  False  False   
412         1304         1  28.0      0      0    7.7750  False  False   True   
414        

NORMALISATION OR MIN MAX SCALER AND STANDARDIZATION

NORMALISATION : Rescalling data from original range so that all values are within the new range of 0 and 1
y = (X - )

In [17]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5,0],[0,10],[1,18]]
scaler = MinMaxScaler()
print(scaler.fit(data))
MinMaxScaler()
print(scaler.data_max_)
print(scaler.transform(data))

MinMaxScaler()
[ 1. 18.]
[[0.         0.11111111]
 [0.25       0.        ]
 [0.5        0.55555556]
 [1.         1.        ]]


STANDARDIZING a dataset involves  re-scalling
sd = sqrt(sum((x-mean)^2)) / count(x))

In [18]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler
data = asarray([[100,0.001],[8,0.05],[50,0.005],[88,0.07],[4,0.1]])
print(data)
scaler = StandardScaler()
scaled = scaler.fit_transform(data)
print(scaled)

[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]
